# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: s

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    # Choose a navigation block
    block: navbar
    # Display the navigation bar?
    enable: true
    # Align menu links: left (l), center (c), or right (r)
    align: c
    # Display your site title or `assets/media/logo*` image in the nav bar?
    show_logo: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: true
    # If `show_translations` is enabled, do you wish to display the current language name?
    show_language: false
    # Let the user override the default light/dark mode of your theme?
    show_day_night: true
    # Let the user search from the nav bar?
    show_search: true
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  copyright:
    notice: 'Â© {year} BK Information Security Club. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  show_translations: true


# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    theme_light: xcode-light
    theme_dark: xcode-dark
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 17
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new)'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
